// AUTO-GENERATED BY tools/convert_ardustim_wheels.py — DO NOT EDIT
//
// Friendly-name lookup table (PatternRef.name_key -> human label).
// Sources:
//   References/wheel_defs.h  SHA256=bc49f73de386fefaf915f0f3ea745381cbbf9f9ce096ca7c227b73026158d711
//   References/ardustim.ino  SHA256=b2c0e791e685485db91e917364426f86b3c2228ea9a5340d87caacee8b6f93aa
// Generated: 2026-05-20T10:58:11Z
//
// Friendly-label string bytes (sum + NUL terminators): 1630 / 2560.
// Note: the `key` pointer in each row is shared with builtin_tables_generated.h
// (same .rodata literal), so the table adds only the human-label strings.
// Lookup helper: PatternLibrary::friendlyName(name_key).

#pragma once

#include <stddef.h>

#include "builtin_tables_generated.h"

#ifndef PROGMEM
#  define PROGMEM
#endif

struct PatternFriendlyName {
    const char* key;       // matches PatternRef::name_key (C identifier)
    const char* friendly;  // human label
};

static const PatternFriendlyName pattern_friendly_names[] PROGMEM = {
    { builtin_tables::dizzy_four_cylinder_name_key, "4 cylinder dizzy" },
    { builtin_tables::dizzy_six_cylinder_name_key, "6 cylinder dizzy" },
    { builtin_tables::dizzy_eight_cylinder_name_key, "8 cylinder dizzy" },
    { builtin_tables::sixty_minus_two_name_key, "60-2 crank only" },
    { builtin_tables::sixty_minus_two_with_cam_name_key, "60-2 crank and cam" },
    { builtin_tables::sixty_minus_two_with_halfmoon_cam_name_key, "60-2 crank and 'half moon' cam" },
    { builtin_tables::thirty_six_minus_one_name_key, "36-1 crank only" },
    { builtin_tables::twenty_four_minus_one_name_key, "24-1 crank only" },
    { builtin_tables::four_minus_one_with_cam_name_key, "4-1 crank wheel with cam" },
    { builtin_tables::eight_minus_one_name_key, "8-1 crank only (R6)" },
    { builtin_tables::six_minus_one_with_cam_name_key, "6-1 crank with cam" },
    { builtin_tables::twelve_minus_one_with_cam_name_key, "12-1 crank with cam" },
    { builtin_tables::fourty_minus_one_name_key, "40-1 crank only (Ford V10)" },
    { builtin_tables::dizzy_four_trigger_return_name_key, "Distributor style 4 cyl 50deg off, 40 deg on" },
    { builtin_tables::oddfire_vr_name_key, "odd fire 90 deg pattern 0 and 135 pulses" },
    { builtin_tables::optispark_lt1_name_key, "GM OptiSpark LT1 360 and 8" },
    { builtin_tables::twelve_minus_three_name_key, "12-3 oddball" },
    { builtin_tables::thirty_six_minus_two_two_two_name_key, "36-2-2-2 H4 Crank only" },
    { builtin_tables::thirty_six_minus_two_two_two_h6_name_key, "36-2-2-2 H6 Crank only" },
    { builtin_tables::thirty_six_minus_two_two_two_with_cam_name_key, "36-2-2-2 Crank and cam" },
    { builtin_tables::fourty_two_hundred_wheel_name_key, "GM 4200 crank wheel" },
    { builtin_tables::thirty_six_minus_one_with_cam_fe3_name_key, "Mazda FE3 36-1 with cam" },
    { builtin_tables::six_g_seventy_two_with_cam_name_key, "Mitsubishi 6g72 with cam" },
    { builtin_tables::buell_oddfire_cam_name_key, "Buell Oddfire CAM wheel" },
    { builtin_tables::gm_ls1_crank_and_cam_name_key, "GM LS1 crank and cam" },
    { builtin_tables::GM_LS_58X_crank_and_4x_cam_name_key, "GM 58x crank and 4x cam" },
    { builtin_tables::lotus_thirty_six_minus_one_one_one_one_name_key, "Odd Lotus 36-1-1-1-1 flywheel" },
    { builtin_tables::honda_rc51_with_cam_name_key, "Honda RC51 with cam" },
    { builtin_tables::thirty_six_minus_one_with_second_trigger_name_key, "36-1 crank with 2nd trigger on teeth 33-34" },
    { builtin_tables::chrysler_ngc_thirty_six_plus_two_minus_two_with_ngc4_cam_name_key, "Chrysler NGC 36+2-2 crank, NGC 4-cyl cam" },
    { builtin_tables::chrysler_ngc_thirty_six_minus_two_plus_two_with_ngc6_cam_name_key, "Chrysler NGC 36-2+2 crank, NGC 6-cyl cam" },
    { builtin_tables::chrysler_ngc_thirty_six_minus_two_plus_two_with_ngc8_cam_name_key, "Chrysler NGC 36-2+2 crank, NGC 8-cyl cam" },
    { builtin_tables::weber_iaw_with_cam_name_key, "Weber-Marelli 8 crank+2 cam pattern" },
    { builtin_tables::fiat_one_point_eight_sixteen_valve_with_cam_name_key, "Fiat 1.8 16V crank and cam" },
    { builtin_tables::three_sixty_nissan_cas_name_key, "Nissan 360 CAS with 6 slots" },
    { builtin_tables::twenty_four_minus_two_with_second_trigger_name_key, "Mazda CAS 24-2 with single pulse outer ring" },
    { builtin_tables::yamaha_eight_tooth_with_cam_name_key, "Yamaha 2002-03 R1 8 even-tooth crank with 1 tooth cam" },
    { builtin_tables::gm_four_tooth_with_cam_name_key, "GM 4 even-tooth crank with 1 tooth cam" },
    { builtin_tables::gm_six_tooth_with_cam_name_key, "GM 6 even-tooth crank with 1 tooth cam" },
    { builtin_tables::gm_eight_tooth_with_cam_name_key, "GM 8 even-tooth crank with 1 tooth cam" },
    { builtin_tables::volvo_d12acd_with_cam_name_key, "Volvo d12[acd] crank with 7 tooth cam" },
    { builtin_tables::mazda_thirty_six_minus_two_two_two_with_six_tooth_cam_name_key, "Mazda 36-2-2-2 with 6 tooth cam" },
    { builtin_tables::mitsubishi_4g63_4_2_name_key, "Mitsubishi 4g63 aka 4/2 crank and cam" },
    { builtin_tables::audi_135_with_cam_name_key, "Audi 135 tooth crank and cam" },
    { builtin_tables::honda_d17_no_cam_name_key, "Honda D17 Crank (12+1)" },
    { builtin_tables::mazda_323_au_name_key, "Mazda 323 AU version" },
    { builtin_tables::daihatsu_3cyl_name_key, "Daihatsu 3+1 distributor (3 cylinders)" },
    { builtin_tables::miata_9905_name_key, "Miata 99-05" },
    { builtin_tables::twelve_with_cam_name_key, "12/1 (12 crank with cam)" },
    { builtin_tables::twenty_four_with_cam_name_key, "24/1 (24 crank with cam)" },
    { builtin_tables::subaru_six_seven_name_key, "Subaru 6/7 crank and cam" },
    { builtin_tables::gm_seven_x_name_key, "GM 7X" },
    { builtin_tables::four_twenty_a_name_key, "DSM 420a" },
    { builtin_tables::ford_st170_name_key, "Ford ST170" },
    { builtin_tables::mitsubishi_3A92_name_key, "Mitsubishi 3A92" },
    { builtin_tables::toyota_4AGE_CAS_name_key, "Toyota 4AGE" },
    { builtin_tables::toyota_4AGZE_name_key, "Toyota 4AGZE" },
    { builtin_tables::suzuki_DRZ400_name_key, "Suzuki DRZ400" },
    { builtin_tables::jeep_2000_4cyl_name_key, "Jeep 2000 4cyl" },
    { builtin_tables::jeep_2000_6cyl_name_key, "Jeep 2000 6 cyl" },
    { builtin_tables::bmw_n20_name_key, "BMW N20" },
    { builtin_tables::viper9602wheel_name_key, "Dodge Viper V10 1996-2002" },
    { builtin_tables::thirty_six_minus_two_with_second_trigger_name_key, "36-2 with 1 tooth cam" },
    { builtin_tables::GM40toothOSS_name_key, "GM 40 tooth OSS wheel for Transmissions" },
};

static constexpr size_t pattern_friendly_name_count =
    sizeof(pattern_friendly_names) / sizeof(pattern_friendly_names[0]);
