// AUTO-GENERATED BY tools/convert_ardustim_wheels.py — DO NOT EDIT
//
// Legacy Wheels[]-index -> name_key migration table.
// Source order: References/ardustim.ino:59-125 (the Wheels[] initializer).
// Generated: 2026-05-20T10:58:11Z
//
// Consumers:
//   * M9.1 legacy serial `L` opcode (Agent E)  — interprets the 1-byte
//     wheel index over the wire by indexing this array.
//   * NVS migration (Agent C / M3.5) — converts a numeric wheel index
//     from an older config blob into the string key actually persisted.
// Lookup helper: PatternLibrary::findByLegacyIndex(idx).

#pragma once

#include <stddef.h>

#ifndef PROGMEM
#  define PROGMEM
#endif

static const char* const pattern_legacy_index_to_key[] PROGMEM = {
    "dizzy_four_cylinder",   // index 0: 4 cylinder dizzy
    "dizzy_six_cylinder",   // index 1: 6 cylinder dizzy
    "dizzy_eight_cylinder",   // index 2: 8 cylinder dizzy
    "sixty_minus_two",   // index 3: 60-2 crank only
    "sixty_minus_two_with_cam",   // index 4: 60-2 crank and cam
    "sixty_minus_two_with_halfmoon_cam",   // index 5: 60-2 crank and 'half moon' cam
    "thirty_six_minus_one",   // index 6: 36-1 crank only
    "twenty_four_minus_one",   // index 7: 24-1 crank only
    "four_minus_one_with_cam",   // index 8: 4-1 crank wheel with cam
    "eight_minus_one",   // index 9: 8-1 crank only (R6)
    "six_minus_one_with_cam",   // index 10: 6-1 crank with cam
    "twelve_minus_one_with_cam",   // index 11: 12-1 crank with cam
    "fourty_minus_one",   // index 12: 40-1 crank only (Ford V10)
    "dizzy_four_trigger_return",   // index 13: Distributor style 4 cyl 50deg off, 40 deg on
    "oddfire_vr",   // index 14: odd fire 90 deg pattern 0 and 135 pulses
    "optispark_lt1",   // index 15: GM OptiSpark LT1 360 and 8
    "twelve_minus_three",   // index 16: 12-3 oddball
    "thirty_six_minus_two_two_two",   // index 17: 36-2-2-2 H4 Crank only
    "thirty_six_minus_two_two_two_h6",   // index 18: 36-2-2-2 H6 Crank only
    "thirty_six_minus_two_two_two_with_cam",   // index 19: 36-2-2-2 Crank and cam
    "fourty_two_hundred_wheel",   // index 20: GM 4200 crank wheel
    "thirty_six_minus_one_with_cam_fe3",   // index 21: Mazda FE3 36-1 with cam
    "six_g_seventy_two_with_cam",   // index 22: Mitsubishi 6g72 with cam
    "buell_oddfire_cam",   // index 23: Buell Oddfire CAM wheel
    "gm_ls1_crank_and_cam",   // index 24: GM LS1 crank and cam
    "GM_LS_58X_crank_and_4x_cam",   // index 25: GM 58x crank and 4x cam
    "lotus_thirty_six_minus_one_one_one_one",   // index 26: Odd Lotus 36-1-1-1-1 flywheel
    "honda_rc51_with_cam",   // index 27: Honda RC51 with cam
    "thirty_six_minus_one_with_second_trigger",   // index 28: 36-1 crank with 2nd trigger on teeth 33-34
    "chrysler_ngc_thirty_six_plus_two_minus_two_with_ngc4_cam",   // index 29: Chrysler NGC 36+2-2 crank, NGC 4-cyl cam
    "chrysler_ngc_thirty_six_minus_two_plus_two_with_ngc6_cam",   // index 30: Chrysler NGC 36-2+2 crank, NGC 6-cyl cam
    "chrysler_ngc_thirty_six_minus_two_plus_two_with_ngc8_cam",   // index 31: Chrysler NGC 36-2+2 crank, NGC 8-cyl cam
    "weber_iaw_with_cam",   // index 32: Weber-Marelli 8 crank+2 cam pattern
    "fiat_one_point_eight_sixteen_valve_with_cam",   // index 33: Fiat 1.8 16V crank and cam
    "three_sixty_nissan_cas",   // index 34: Nissan 360 CAS with 6 slots
    "twenty_four_minus_two_with_second_trigger",   // index 35: Mazda CAS 24-2 with single pulse outer ring
    "yamaha_eight_tooth_with_cam",   // index 36: Yamaha 2002-03 R1 8 even-tooth crank with 1 tooth cam
    "gm_four_tooth_with_cam",   // index 37: GM 4 even-tooth crank with 1 tooth cam
    "gm_six_tooth_with_cam",   // index 38: GM 6 even-tooth crank with 1 tooth cam
    "gm_eight_tooth_with_cam",   // index 39: GM 8 even-tooth crank with 1 tooth cam
    "volvo_d12acd_with_cam",   // index 40: Volvo d12[acd] crank with 7 tooth cam
    "mazda_thirty_six_minus_two_two_two_with_six_tooth_cam",   // index 41: Mazda 36-2-2-2 with 6 tooth cam
    "mitsubishi_4g63_4_2",   // index 42: Mitsubishi 4g63 aka 4/2 crank and cam
    "audi_135_with_cam",   // index 43: Audi 135 tooth crank and cam
    "honda_d17_no_cam",   // index 44: Honda D17 Crank (12+1)
    "mazda_323_au",   // index 45: Mazda 323 AU version
    "daihatsu_3cyl",   // index 46: Daihatsu 3+1 distributor (3 cylinders)
    "miata_9905",   // index 47: Miata 99-05
    "twelve_with_cam",   // index 48: 12/1 (12 crank with cam)
    "twenty_four_with_cam",   // index 49: 24/1 (24 crank with cam)
    "subaru_six_seven",   // index 50: Subaru 6/7 crank and cam
    "gm_seven_x",   // index 51: GM 7X
    "four_twenty_a",   // index 52: DSM 420a
    "ford_st170",   // index 53: Ford ST170
    "mitsubishi_3A92",   // index 54: Mitsubishi 3A92
    "toyota_4AGE_CAS",   // index 55: Toyota 4AGE
    "toyota_4AGZE",   // index 56: Toyota 4AGZE
    "suzuki_DRZ400",   // index 57: Suzuki DRZ400
    "jeep_2000_4cyl",   // index 58: Jeep 2000 4cyl
    "jeep_2000_6cyl",   // index 59: Jeep 2000 6 cyl
    "bmw_n20",   // index 60: BMW N20
    "viper9602wheel",   // index 61: Dodge Viper V10 1996-2002
    "thirty_six_minus_two_with_second_trigger",   // index 62: 36-2 with 1 tooth cam
    "GM40toothOSS",   // index 63: GM 40 tooth OSS wheel for Transmissions
};

static constexpr size_t pattern_legacy_index_count =
    sizeof(pattern_legacy_index_to_key) / sizeof(pattern_legacy_index_to_key[0]);
